DO NOT MERGE: Migrate to Vite
mdn/todo-react pull request #97
Opened 2023-12-13 10:18 UTC by mxmason

## Description

As part of mdn/mdn#474, this PR migrates the app away from `create-react-app` and onto `Vite`. This migration necessitates a few different kinds of changes. Among them:
- renaming `.js` files to `.jsx`
- removing default `React` imports
- trading `public/index.html` for a root-level `index.html`

While this PR has no dependencies, it's probably best to hold off until the tutorial in mdn/mdn#474 is fully updated.

2023-12-14 09:19 UTC, chrisdavidmills commented
Sounds good @mxmason! Once all the docs updates are done, ping me again and I'll review this.

2023-12-20 11:59 UTC, chrisdavidmills requested changes
@mxmason I had a quick sweep through, and noticed some differences in the code base on here, versus the new one built up from your new tutorials. Shouldn't take a long time to fix up; just make sure the code bases are equivalent. Thanks!

2023-12-20 11:59 UTC, chrisdavidmills commented on src/App.jsx
> +    if (tasks.length < prevTaskLength) {
In my version of `App.jsx`:

- The `<ul>` has a `role` of `list`.
- The `editTask` function has full comments; the one in this repo has comments incomplete or missing

2023-12-20 11:59 UTC, chrisdavidmills commented on src/components/Form.jsx
> +import { useState } from "react";
In my form component:

- `handleSubmit()` is quite different; we don't have the `trim()` check anymore.
- The events use `event` rather than `e`

2023-12-20 11:59 UTC, chrisdavidmills commented on src/components/Todo.jsx
> +import { useEffect, useRef, useState } from "react";
In my Todo file:

- As a general point, I noticed that in the new files generated from Vite, we are doing separate `export default` statements at the bottom fo the time, whereas in the ones in this repo we have `export default` before the function name in the definition.
- Again, our new Vite code doesn't include the `trim()` check
- The editing template `<input>` no longer has a `placeholder` in the new code.
-

2023-12-20 11:59 UTC, chrisdavidmills commented on src/index.css
> +*:focus-visible {
My index CSS file is significantly longer than the one in here, by about 50 lines.

2023-12-21 03:08 UTC, mxmason reviewed
Heya, @chrisdavidmills! This is ready for another look :)

While I definitely had a few discrepancies to fix, some of what you're seeing confuses me. I don't know how you ended up with a 50-line difference in `index.css`, for example. The CSS in that file now is copied directly from the updated tutorial.  I went back and referenced each branch to try to achieve parity with the tutorial – I've fixed the `export` patterns and the names of the `event` variables, for instance.

Other differences you're seeing might come from the fact that this code has been edited by people other than me. I never mention `placeholder` in the tutorial because of its myriad accessibility problems, so I wouldn't have noticed that someone snuck that in there if you hadn't said anything. Same for the `.trim()` functionality  – we called that out as an exercise for the reader in the tutorial. I've added comments to hopefully prevent people from re-introducing trim() as a fix.

2023-12-21 08:14 UTC, chrisdavidmills commented
> Heya, @chrisdavidmills! This is ready for another look :)
> 
> While I definitely had a few discrepancies to fix, some of what you're seeing confuses me! I don't know how you ended up with 50 extra lines in `index.css`, for example. The CSS in that file now is copied directly from the updated tutorial. I went back and referenced each branch to try to achieve parity with the tutorial – I've fixed the `export` patterns and the names of the `event` variables, for instance.
> 
> Other differences you're seeing might come from the fact that this code has been edited by people other than me. I never mention `placeholder` in the tutorial because of its myriad accessibility problems, so I wouldn't have noticed that someone snuck that in there if you hadn't said anything. Same for the `.trim()` functionality – we called that out as an exercise for the reader in the tutorial. I've added comments to hopefully prevent people from re-introducing trim() as a fix.

@mxmason Nice work! This looks good to me now.

I hadn't reckoned on other people adding features to the repo not included in the tutorial! I didn't word it very well, but yeah, by comment was more supposed to be "why is this placeholder stuff here?" rather than "why haven't we included it?" I know that an a11y like your good self wouldn't include such things.

The difference in CSS file size was due to my code editor automatically adding line breaks between each rule. My bad!

2023-12-21 08:15 UTC, chrisdavidmills approved these changes
Let's-a-go!

2023-12-21 08:20 UTC, teoli2003 approved these changes

2023-12-21 09:32 UTC, merged